## Server properties
# Server port
server.port=${WEBSITES_PORT:8080}
# Display name of the application
server.servlet.application-display-name=${info.app.name}
# Base path of the api endpoints
#server.servlet.context-path=${APP_CONTEXT_PATH:}
# Session timeout (seconds)
server.servlet.session.timeout=${SESSION_TIMEOUT_SECONDS:3600}
# Server whitelabel error
server.error.whitelabel.enabled=false

## Actuator properties
# Base path of the actuator endpoints
management.endpoints.web.base-path=${ACTUATOR_MANAGEMENT_ENDPOINTS_WEB_BASE_PATH:/manage}
# Enable actuator endpoints
management.endpoints.enabled-by-default=${ACTUATOR_MANAGEMENT_ENDPOINTS_ENABLED:true}
# Expose health and info endpoints only. To expose all the Actuator endpoints put *
management.endpoints.web.exposure.include=${ACTUATOR_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDED:health,info}
# Show Health details: never, always, when-authorized
management.endpoint.health.show-details=${ACTUATOR_MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}
# Show Redis health
management.health.redis.enabled=${ACTUATOR_MANAGEMENT_REDIS_HEALTH_ENABLED:false}
# Info
management.info.java.enabled=${ACTUATOR_MANAGEMENT_INFO_JAVA_ENABLED:false}
management.info.env.enabled=${ACTUATOR_MANAGEMENT_INFO_ENV_ENABLED:false}
info.app.name=${APP_NAME:csl-identity-service}
info.app.description=${APP_DESCRIPTION:csl-identity-service description here}
info.app.version=${APP_VERSION:csl-identity-service-0.0.1-SNAPSHOT}
info.app.mvnw.version=${MVN_WRAPPER_VERSION:Apache Maven 3.8.6}
info.app.spring-boot.version=${SPRING_BOOT_VERSION:Spring Boot 3.1.0}

## Logging properties
# Root
logging.level.root=${ROOT_LOGGING_LEVEL:INFO}
# Spring Framework
logging.level.org.springframework=${ORG_SPRINGFRAMEWORK_LOGGING_LEVEL:INFO}
logging.level.org.springframework.security=${ORG_SPRINGFRAMEWORK_SECURITY_LOGGING_LEVEL:INFO}
logging.level.org.springframework.session=${ORG_SPRINGFRAMEWORK_SESSION_LOGGING_LEVEL:INFO}
# csl-identity-service
logging.level.uk.gov.cabinetoffice.csl=${UK_GOV_CABINETOFFICE_LOGGING_LEVEL:DEBUG}

## Flyway properties
spring.flyway.locations=classpath:db/migration/{vendor}
spring.flyway.out-of-order=true

## JPA properties
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:none}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=${JPA_HIBERNATE_ENABLE_LAZY_LOAD_NO_TRANS:true}

## DB connection properties
# H2 in-memory DB for build and unit testing
database.host=${DATABASE_HOST:jdbc:h2:mem}
database.name=${DATABASE_NAME:identity}
database.use-ssl=${DATABASE_USESSL:false}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.url=${DATASOURCE_URL:${database.host}:${database.name};MODE=MySQL;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DATASOURCE_USERNAME:sa}
spring.datasource.password=${DATASOURCE_PASSWORD:sa}

# H2 file-based DB for local development
#database.host=${DATABASE_HOST:jdbc:h2}
#database.name=${DATABASE_NAME:~/dev/H2_db/identity_h2_db}
#database.use-ssl=${DATABASE_USESSL:false}
#spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
#spring.datasource.url=${DATASOURCE_URL:${database.host}:${database.name};MODE=MySQL;DB_CLOSE_DELAY=-1}
#spring.datasource.username=${DATASOURCE_USERNAME:sa}
#spring.datasource.password=${DATASOURCE_PASSWORD:sa}

# MySql DB for local dev, test and prod environments
#database.host=${DATABASE_HOST:jdbc:mysql://localhost:3306}
#database.name=${DATABASE_NAME:identity}
#database.use-ssl=${DATABASE_USESSL:false}
#spring.datasource.driver-class-name=${DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
#spring.datasource.url=${DATASOURCE_URL:${database.host}/${database.name}?useSSL=${database.use-ssl}&requireSSL=false}
#spring.datasource.username=${DATASOURCE_USERNAME:root}
#spring.datasource.password=${DATASOURCE_PASSWORD:my-secret-pw}

## Redis cache properties for caching the service-token
spring.data.redis.repositories.enabled=false
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.type=${CACHE_TYPE:redis}
spring.cache.redis.key-prefix=${REDIS_KEY_PREFIX:csl-identity_}
spring.cache.redis.use-key-prefix=${REDIS_USE_KEY_PREFIX:true}
spring.cache.redis.cache-null-values=${REDIS_CACHE_NULL_VALUES:false}
spring.cache.redis.time-to-live=${REDIS_CACHE_TTL_MS:43200000}
spring.cache.redis.enable-statistics=${REDIS_CACHE_ENABLE_STATISTICS:false}
spring.session.redis.namespace=spring:session
spring.session.redis.flush-mode=on_save

spring.thymeleaf.cache=${THYMELEAF_CACHE:true}
spring.thymeleaf.check-template=${THYMELEAF_CHECK_TEMPLATE:true}
spring.messages.basename=i18n/messages

## Jackson properties
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

## lpg-services properties
lpg.uiUrl=${LPG_UI_URL:http://localhost:3001}
lpg.SignoutEndpoint=${LPG_UI_SIGNOUT_ENDPOINT:/api/caches/user/%s/logout}
lpg.Signout=${LPG_UI_SIGNOUT:/sign-out}
lpg.contactEmail=${CONTACT_EMAIL:support@governmentcampus.co.uk}
lpg.contactNumber=${CONTACT_NUMBER:020 3640 7985}

## oAuth2.0 properties
oauth2.jwtKey=${JWT_KEY:ChangeMe}
oauth2.serviceUrl=${OAUTH2_SERVICE_URL:http://localhost:8080}
oauth2.tokenUrl=${OAUTH2_TOKEN_ENDPOINT:/oauth2/token}
oauth2.clientId=${CLIENT_ID:ChangeMe}
oauth2.clientSecret=${CLIENT_SECRET:ChangeMe}
oauth2.refresh.serviceTokenCache.beforeSecondsToExpire=${REFRESH_SERVICE_TOKEN_CACHE_SECONDS_BEFORE_TO_EXPIRE:5}

## csl-identity-service properties
time.zoneId=${TIME_ZONE_ID:UTC}
textEncryption.encryptionKey=${ENCRYPTION_KEY:0123456789abcdef0123456789abcdef}
templates.assetCdn=${ASSET_CDN:ChangeMe}
authenticationSuccess.targetUrl=${AUTHENTICATION_SUCCESS_TARGET_URL:http://localhost:3001}

## Maintenance page properties
maintenancePage.enabled=${MAINTENANCE_PAGE_ENABLED:false}
maintenancePage.contentLine1=${MAINTENANCE_PAGE_CONTENT_LINE_1:The learning website is undergoing scheduled maintenance.}
maintenancePage.contentLine2=${MAINTENANCE_PAGE_CONTENT_LINE_2:It will be unavailable between the hours of 6pm to 8pm on Wednesday 6th September 2023.}
maintenancePage.contentLine3=${MAINTENANCE_PAGE_CONTENT_LINE_3:Apologies for the inconvenience.}
maintenancePage.contentLine4=${MAINTENANCE_PAGE_CONTENT_LINE_4:If the maintenance period is extended, further information will be provided here.}
maintenancePage.skipForUsers=${MAINTENANCE_PAGE_SKIP_FOR_USERS:tester1@domain.com,tester2@domain.com}
maintenancePage.skipForUris=${MAINTENANCE_PAGE_SKIP_FOR_URIS:/health,/info,/maintenance,/error,/logout,/cookies,/privacy,/accessibility-statement,/contact-us,/webjars,/css,/img,/js,/favicon.ico,/oauth2/token,/oauth2/introspect,/oauth2/revoke,/identity/resolve,/reset-cache,/api/identities,/signup/chooseOrganisation,/signup/enterToken,/account/verify/agency,/account/reactivate/updated,/account/email/updated,/account/email/update/error}

## User registration properties
invite.url=${oauth2.serviceUrl}/signup/%s
invite.validityInSeconds=${INVITE_VALIDITY_SECONDS:259200}
invite.durationAfterReRegAllowedInSeconds=${DURATION_AFTER_REREG_ALLOWED_SECONDS:86400}

## Password reset properties
reset.url=${oauth2.serviceUrl}/reset/%s
reset.validityInSeconds=${RESET_VALIDITY_SECONDS:86400}
reset.durationAfterResetAllowedInSeconds=${DURATION_AFTER_RESET_ALLOWED_SECONDS:3600}

## User account properties
accountValidation.passwordPattern=${PASSWORD_PATTERN:^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}$}
account.lockout.maxLoginAttempts=${ACCOUNT_LOCKOUT_MAX_LOGIN_ATTEMPTS:5}

## User account reactivation properties
reactivation.reactivationUrl=${oauth2.serviceUrl}/account/reactivate/
reactivation.validityInSeconds=${REACTIVATION_VALIDITY_SECONDS:86400}
reactivation.durationAfterReactivationAllowedInSeconds=${DURATION_AFTER_REACTIVATION_ALLOWED_SECONDS:3600}

## Email update properties
emailUpdate.urlFormat=${oauth2.serviceUrl}/account/email/verify/%s?redirect=true
emailUpdate.validityInSeconds=${EMAIL_UPDATE_VALIDITY_SECONDS:86400}
emailUpdate.durationAfterEmailUpdateAllowedInSeconds=${DURATION_AFTER_EMAIL_UPDATE_ALLOWED_SECONDS:3600}

## Gov Notify Service properties
govNotify.key=${GOV_NOTIFY_API_KEY:ChangeMe}
govNotify.template.invite=${GOV_NOTIFY_INVITE_TEMPLATE_ID:ChangeMe}
govNotify.template.reset=${GOV_NOTIFY_RESET_TEMPLATE_ID:ChangeMe}
govNotify.template.resetSuccessful=${GOV_NOTIFY_RESET_SUCCESSFUL_TEMPLATE_ID:ChangeMe}
govNotify.template.passwordUpdate=${GOV_NOTIFY_PASSWORD_UPDATE_TEMPLATE_ID:ChangeMe}
govNotify.template.emailUpdate=${GOV_NOTIFY_EMAIL_UPDATE_TEMPLATE_ID:f4c2ece1-5159-4736-92cb-4fe0df719308}
govNotify.template.reactivation=${GOV_NOTIFY_REACTIVATION_TEMPLATE_ID:ChangeMe}

## CivilServantRegistryService properties
civilServantRegistry.serviceUrl=${CIVIL_SERVANT_REGISTRY_SERVICE_URL:http://localhost:9002}
civilServantRegistry.civilServantUrl=/civilServants
civilServantRegistry.getOrganisationsMaxPageSize=${CIVIL_SERVANT_REGISTRY_ORGANISATION_MAX_PAGE_SIZE:200}
civilServantRegistry.organisationalUnitsUrl=/v2/organisationalUnits
civilServantRegistry.agencyTokensUrl=/agencyTokens
civilServantRegistry.domainsUrl=/domains
civilServantRegistry.allowListDomains.cache.ttlSeconds=${ALLOWLIST_DOMAINS_CACHE_TTL_SECONDS:43200}
civilServantRegistry.organisations.cache.ttlSeconds=${ORGANISATIONS_CACHE_TTL_SECONDS:43200}

## csl-service properties
cslService.serviceUrl=${CSL_SERVICE_URL:http://localhost:9003}
cslService.activateUser=/api/user/%s/activate
cslService.updateEmail=/api/user/%s/updateEmail/%s

## NSG
nsgFlag=${NSG_FLAG:false}
